### ISSUE TITLE
different template, how to make sure the one is active, and others are hidden

### ISSUE THREAD

**Issue by ericxin1982** [shaunlee/alpinejs-router#10]
Hi @shaunlee 

I saw the code,  how to make sure the active template is up, and others are hidden?

Thanks
Eric Xin

**Comment by shaunlee** [comment]
Hi @ericxin1982 

See the `src/index.js` line 179 to 183, each time the `location.href` changes the router will show the matched(active) template and remove others.

**Comment by ericxin1982** [comment]
Thanks!
