### ISSUE TITLE
Anchors don't work in hash mode

### ISSUE THREAD

**Issue by berndca** [shaunlee/alpinejs-router#12]
I don't seem to be able to navigate to an anchor:

<h1 id="my-anchor">Anchor Headline</h1>

when I'm in hash mode. 

The URL would look like this:

http://127.0.0.1:5500/app/#/test#my-anchor

Unfortunately due to the restrictions of the external static hoster I have to use hash mode. Do you think you could support anchors in hash mode?

Thanks, Bernd

**Comment by shaunlee** [comment]
@berndca You may want to use the default "web" mode.
