### ISSUE TITLE
Provide API of `$router` in JS

### ISSUE THREAD

**Issue by docweirdo** [shaunlee/alpinejs-router#2]
Hey, thanks for your work.

I am trying to do something in the EventListener of `alpine:init` depending on the current route. I do not seem to be able to do that, since the magic property `$router` is not available in JS context. 

Is there any way to expose/export an instance of the `route` object of index.js so the same functions which are accessible in HTML are accessible in JS?

**Comment by shaunlee** [comment]
@docweirdo I've added some examples of how to use it, see the 'In Directive' part. I hope this will help you.

https://github.com/shaunlee/alpinejs-router/tree/master/examples

**Comment by docweirdo** [comment]
Thank you, the examples are helpful and provide a way to deal with what I am trying to do.

However, I still wonder if it is possible to have a `Router` object in plain JS, just like there is access to the `Alpine` object. 
To give an example, I am imagining a snippet like this to work:
``` javascript
document.addEventListener('alpine:init', () => {
  
    if (Router.is('/:orderID(\d+)')){
        Alpine.store('state, 'order');
    }
});
```
Right now, as it is, the only way to have something like a `Router` object is to pass it to JS functions from the HTML code using the `$router` magic, which works,  but isn't as intuitive. Example:
``` html
<div x-init="setState($router)">
    ...
</div>
```
``` javascript
function setState(router){
    if (router.is('/:orderID(\d+)')){
        Alpine.store('state, 'order');
    }
}
```

Let me know if I'm making any sense to you.

**Comment by shaunlee** [comment]
Try this way:
`<body x-data x-init="Alpine.$router = $router">`
or
`<body x-data x-init="window.$router = $router">`

**Comment by docweirdo** [comment]
Thank you for the response, sorry for the delay.

I've tried your suggestion, it does enable me to use e.g. `Alpine.router` in JS context. Problem still is that I can not put logic depending on the router in the `alpine:init` event handler since `<body x-init="...">` is executed after `alpine:init` fires.

I'd therefore like to know if it's possible for you to include such an export in your library, for example, could you amend `index.js` to define a `router` property on the Alpine instance?
``` js
export default function (Alpine) {
  const router = new Router()
  // ...
  Alpine.router = router
}
```

I can of course still emit my own event in `<body x-init="..."` after binding the router to the Alpine instance and act accordingly, but it would be nicer to just have it included in the library, since it is in my view a frequent use case to access the router in JS context, especially at the initialisation of Alpine.

**Comment by shaunlee** [comment]
Added `Alpine.$router`, please check the latest version.

**Comment by docweirdo** [comment]
Fantastic, seems to work as intended. Thank you very much.

As a note to people stumbling upon the same issue, it is still not possible to use `Alpine.$router` within the `alpine:init` event handler directly, since the attribute is added by a handler listening to the same event. I recommend using this hack:

``` js 
document.addEventListener('alpine:init', () => {
  window.setTimeout(() =>{
    console.log(Alpine.$router)
  },0);
}
```
