### ISSUE TITLE
`$router.params` set to false when accessing route directly

### ISSUE THREAD

**Issue by docweirdo** [shaunlee/alpinejs-router#3]
Copying the example from README.md, the value of `$router.params` is set to `false` when accessing the route `/hello/world` directly without using the link provided by `x-link`.

**Comment by shaunlee** [comment]
Thanks for the heads up, I've updated it to an empty object.

52971aac925ee88623c33610e27d29eeadccaf3d

**Comment by docweirdo** [comment]
Is it not possible to have the parameters even when that route was accessed directly?

**Comment by shaunlee** [comment]
Here's how the `$router.params` works:

`x-route="/hello/world"` -> `$router.params` === `{}`
`x-route="/path/to/:arg1/:arg2/:arg3"` -> `$router.params` === `{"arg1": "...", "arg2": "...", "arg3": "..."}`

I'm not sure if what you want is the `URL` query? Like so:

`/users?page=1&status=2` -> `$router.query` === `{"page": "1", "status": "2"}`

**Comment by shaunlee** [comment]
Probably because the template in `Alpine.js` can only have one root element. Change it like this:

```html
<template x-route="/hello/:user">
    <div>Hello <span x-text="$router.params.user"></span></div>
</template>
```

and make sure you set the `x-data` directive in the `<body ... >` like so `<body x-data ...>`, to make all `Alpine.js` code work properly.

**Comment by jgauna** [comment]
I am facing exactly the same issue. I am using Vite and [async-alpine](https://github.com/Accudio/async-alpine), which could be the problem. I've used your code plus I double-checked the directive in the body

**index.html**
```html
  <body x-data x-init="$router.config({ mode: 'hash' })">
    <div id="app" class="login">
      <div ax-load ax-load-src="js/components/Home/home.js" x-data="home()" x-html="view" x-ignore></div>
    </div>

    <script type="module" src="/main.js"></script>
  </body>
```

**home.js component**
```html
<div ax-load ax-load-src="js/components/ChildModule/main.js" x-data="ChildModule()" x-html="view" x-ignore></div>

<a x-link href="/hello/world">Hello World</a>
<template x-route="/hello/:user">
  <div>Hello <span x-text="$router.params.user"></span></div> <!-- @IMPORTANT: @BUG When I refresh the params are missing and it shows just "Hello" -->
</template>
```

**Comment by docweirdo** [comment]
Sorry for the delay. It took me some time to get around to testing this again. 
This time, I've used the example @shaunlee provided in `examples`. 

Accessing the path `hello/Shaunlee` directly leads to the following result:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/43937002/204268215-0300be35-adfd-4f86-9a93-d087d107f50d.png">

**Comment by shaunlee** [comment]
@docweirdo Please try replacing the URL from `http://127.0.0.1:5500/hello/Shaunlee` to `http://127.0.0.1:5500/#/hello/Shaunlee` as the example uses the hash mode `<body x-data x-init="$router.config({ mode: 'hash' })"`
<img width="901" alt="Screenshot 2022-11-28 at 19 43 13" src="https://user-images.githubusercontent.com/655635/204270739-f7012d88-912d-46be-bce9-fc9c0569c3a1.png">

@jgauna Are you experiencing the same situation?

**Comment by docweirdo** [comment]
I forgot to mention that I for this screenshot I had changed it to the default rooting mode, sorry. In fact, when changing it back to `hash`, it works as intended. 

The issue does persist in the recommended HTML5 mode.

**Comment by shaunlee** [comment]
Fixed, please check the latest version.

Thank you @docweirdo @jgauna

**Comment by docweirdo** [comment]
Wonderful, thank you very much, the example works now with `mode` set to  `'web'` as well.
