### ISSUE TITLE
$router is not defined

### ISSUE THREAD

**Issue by PaulRichez** [shaunlee/alpinejs-router#6]
$router is not defined

with both cdn.min.js and es6.min.js

Used with vite js and electron js

**Comment by shaunlee** [comment]
Let me see your code

**Comment by PaulRichez** [comment]
![image](https://user-images.githubusercontent.com/37926689/210956274-34c01099-ccd0-4b7f-9b66-d525e93629a2.png)
Hummm, that not the same error, just router look doesn't work now

**Comment by shaunlee** [comment]
Don't forget the `x-data` directive: `<body x-data>`.

**"Everything in Alpine starts with an x-data directive."**
