### ISSUE TITLE
Page reload changes location to server root

### ISSUE THREAD

**Issue by swavy-dev** [shaunlee/alpinejs-router#7]
Hi, I like your approach and would like to use your alpinejs-router in a project. However I need a working router for a page in a sub directory of the servers root like /calculator/. When I load your example the first time the URL is 

http://127.0.0.1:5500/examples/index.html, however all routes in the example transform the URL to http://127.0.0.1:5500/#/ instead of http://127.0.0.1:5500/examples/#/.

Is there any way I can configure the router to work in a sub directory of the servers root?

Thanks, Bernd

**Comment by shaunlee** [comment]
Have you tried configuring the base?
<img width="759" alt="Screenshot 2023-04-10 at 11 01 22" src="https://user-images.githubusercontent.com/655635/230817000-2c4abfa7-d567-483a-8085-9f97e7a9fc4a.png">

**Comment by swavy-dev** [comment]
Thanks. I didn't see that.
